/*
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
/*
    Submission Date: 2018-05-02
    Runtime: 9 ms
    Difficulty: EASY
*/
#include <iostream>
#include <unordered_map>

using namespace std;

class Solution {
 public:
  char findTheDifference(string s, string t) {
    unordered_map<char, int> m;
    for (auto e : s) m[e]++;
    for (auto e : t) {
      if (m.count(e)) {
        if (m[e] == 0) return e;
        m[e]--;
      } else {
        return e;
      }
    }
    return '\0';
  }
};

int main() { return 0; }